export const EXAMPLE_JSON = {
  date: "2021-10-27T07:49:14.896Z",
  hasError: false,
  fields: [
    {
      id: "4c212130",
      prop: "iban",
      value: "DE81200505501265402568",
      hasError: false,
    },
  ],
};

export const ANOTHER_EXAMPLE_JSON = [
  {
    _id: "65df2c522882bbbf58d91ef2",
    index: 0,
    guid: "357b92f3-efff-462e-a2ba-3401fce836d3",
    isActive: false,
    balance: "$3,201.03",
    picture: "http://placehold.it/32x32",
    age: 25,
    eyeColor: "brown",
    name: "Richard Barton",
    gender: "male",
    company: "HYPLEX",
    email: "richardbarton@hyplex.com",
    phone: "+1 (892) 501-2322",
    address: "369 Cedar Street, Morriston, Oklahoma, 6495",
    about:
      "Commodo aliquip ut culpa cillum cillum duis. Ullamco irure incididunt esse nisi incididunt aliqua amet aliquip qui adipisicing et minim dolore consequat. Nulla anim in proident ipsum anim eu non duis. Amet duis sunt irure qui tempor ipsum voluptate laborum anim.\r\n",
    registered: "2024-01-09T03:36:31 -01:00",
    latitude: -49.07707,
    longitude: -147.540173,
    tags: [
      "esse",
      "consectetur",
      "dolor",
      "eiusmod",
      "magna",
      "nostrud",
      "incididunt",
    ],
    friends: [
      {
        id: 0,
        name: "Myers Hoover",
      },
      {
        id: 1,
        name: "Lucile Lynch",
      },
      {
        id: 2,
        name: "Wiley Munoz",
      },
    ],
    greeting: "Hello, Richard Barton! You have 10 unread messages.",
    favoriteFruit: "banana",
  },
  {
    _id: "65df2c528d1e82723ceb2511",
    index: 1,
    guid: "feece6ed-d9cb-431b-b0b9-db53701dce07",
    isActive: true,
    balance: "$3,765.36",
    picture: "http://placehold.it/32x32",
    age: 36,
    eyeColor: "green",
    name: "Vega Sanchez",
    gender: "male",
    company: "QUINEX",
    email: "vegasanchez@quinex.com",
    phone: "+1 (913) 421-3215",
    address: "983 Nostrand Avenue, Cornucopia, District Of Columbia, 4282",
    about:
      "Ullamco irure voluptate consectetur sit ex ut ut in aute. Eu deserunt enim sint ad non. Tempor ad aliqua proident consequat cupidatat consectetur dolor cillum labore. Officia dolor deserunt eiusmod adipisicing est culpa non proident in nostrud cillum consectetur ex.\r\n",
    registered: "2015-02-05T12:18:52 -01:00",
    latitude: 36.141796,
    longitude: 75.334587,
    tags: ["laborum", "minim", "anim", "nostrud", "anim", "magna", "ullamco"],
    friends: [
      {
        id: 0,
        name: "Prince Marks",
      },
      {
        id: 1,
        name: "Maxwell Johnson",
      },
      {
        id: 2,
        name: "April Patterson",
      },
    ],
    greeting: "Hello, Vega Sanchez! You have 8 unread messages.",
    favoriteFruit: "strawberry",
  },
  {
    _id: "65df2c5202d98770ed96b06b",
    index: 2,
    guid: "1dc306f8-2d32-4fac-b3c6-88a43d4ae7ac",
    isActive: true,
    balance: "$1,237.56",
    picture: "http://placehold.it/32x32",
    age: 30,
    eyeColor: "green",
    name: "Lyons Reilly",
    gender: "male",
    company: "SIGNITY",
    email: "lyonsreilly@signity.com",
    phone: "+1 (850) 480-3829",
    address: "411 Allen Avenue, Bancroft, Nevada, 2471",
    about:
      "Ad nostrud consequat officia esse consequat sunt anim deserunt dolor mollit aute. Qui incididunt nostrud ullamco eu cupidatat in ut do ex ea voluptate excepteur. Magna occaecat id deserunt duis elit esse. In est ut exercitation labore cillum voluptate. Irure ipsum sunt culpa aute eu labore in. Ipsum ex deserunt anim eu non deserunt aute nisi id. Reprehenderit excepteur adipisicing ea fugiat duis esse et ex non est laboris consectetur.\r\n",
    registered: "2018-02-12T03:25:04 -01:00",
    latitude: 74.253559,
    longitude: 173.782402,
    tags: ["nulla", "est", "occaecat", "ad", "id", "dolore", "elit"],
    friends: [
      {
        id: 0,
        name: "Summers Wiggins",
      },
      {
        id: 1,
        name: "Ware Cox",
      },
      {
        id: 2,
        name: "Compton Cruz",
      },
    ],
    greeting: "Hello, Lyons Reilly! You have 1 unread messages.",
    favoriteFruit: "strawberry",
  },
  {
    _id: "65df2c52f5d0dd9afc6b7f2f",
    index: 3,
    guid: "50d6d980-5a96-48ba-ac02-71f41f98a766",
    isActive: false,
    balance: "$1,435.92",
    picture: "http://placehold.it/32x32",
    age: 37,
    eyeColor: "blue",
    name: "Mercedes Sims",
    gender: "female",
    company: "MOLTONIC",
    email: "mercedessims@moltonic.com",
    phone: "+1 (929) 438-2869",
    address: "460 Vanderveer Street, Nadine, Kentucky, 7706",
    about:
      "Incididunt velit sunt commodo tempor aliquip et exercitation laborum aliquip. Ex reprehenderit fugiat qui est nulla ex cupidatat aliqua cupidatat minim culpa non. Occaecat est nulla ipsum officia sint cillum reprehenderit qui id Lorem veniam ipsum est. Aute dolor sunt exercitation nostrud veniam duis quis culpa eu.\r\n",
    registered: "2018-05-20T02:55:03 -02:00",
    latitude: -3.232202,
    longitude: -31.72459,
    tags: [
      "minim",
      "proident",
      "tempor",
      "tempor",
      "culpa",
      "deserunt",
      "labore",
    ],
    friends: [
      {
        id: 0,
        name: "Blevins Paul",
      },
      {
        id: 1,
        name: "Doreen Owens",
      },
      {
        id: 2,
        name: "Massey Dyer",
      },
    ],
    greeting: "Hello, Mercedes Sims! You have 4 unread messages.",
    favoriteFruit: "apple",
  },
  {
    _id: "65df2c52b271b6bdbef17b3a",
    index: 4,
    guid: "e9b485bc-0f2b-4256-9885-ebee9cb3c2f8",
    isActive: false,
    balance: "$1,174.85",
    picture: "http://placehold.it/32x32",
    age: 39,
    eyeColor: "blue",
    name: "Farrell Mccray",
    gender: "male",
    company: "FITCORE",
    email: "farrellmccray@fitcore.com",
    phone: "+1 (953) 468-2603",
    address: "761 Fanchon Place, Robinson, Tennessee, 5236",
    about:
      "Nisi aute commodo exercitation do mollit cupidatat. Et esse exercitation Lorem duis irure quis sint commodo non duis. Eiusmod minim adipisicing elit ut reprehenderit velit tempor reprehenderit ut mollit minim dolor. Irure excepteur ut exercitation tempor culpa incididunt cillum nostrud est nostrud enim.\r\n",
    registered: "2022-05-11T10:54:01 -02:00",
    latitude: -21.71021,
    longitude: 157.46607,
    tags: [
      "tempor",
      "sunt",
      "nisi",
      "nostrud",
      "aliqua",
      "dolore",
      "excepteur",
    ],
    friends: [
      {
        id: 0,
        name: "Ayers Ramos",
      },
      {
        id: 1,
        name: "Evelyn Bender",
      },
      {
        id: 2,
        name: "Alisha Mills",
      },
    ],
    greeting: "Hello, Farrell Mccray! You have 7 unread messages.",
    favoriteFruit: "strawberry",
  },
  {
    _id: "65df2c52a9a57a75605e3c84",
    index: 5,
    guid: "5aa61287-97d8-40c2-b11c-1d428998150b",
    isActive: false,
    balance: "$3,624.45",
    picture: "http://placehold.it/32x32",
    age: 32,
    eyeColor: "blue",
    name: "Mendoza Pollard",
    gender: "male",
    company: "SONGLINES",
    email: "mendozapollard@songlines.com",
    phone: "+1 (874) 451-2185",
    address: "413 Wilson Avenue, Conway, Missouri, 8988",
    about:
      "Anim qui aliquip voluptate occaecat laborum proident cupidatat magna irure laborum do. Amet laboris occaecat est aute culpa qui consectetur. Ex exercitation mollit laboris tempor minim excepteur proident est minim nostrud. Elit aliqua eu excepteur eiusmod eu duis in. Pariatur proident enim non ipsum laborum proident officia nulla eu quis.\r\n",
    registered: "2015-05-22T04:31:27 -02:00",
    latitude: 60.090626,
    longitude: -68.495477,
    tags: ["est", "mollit", "veniam", "ea", "excepteur", "deserunt", "mollit"],
    friends: [
      {
        id: 0,
        name: "Holden Gaines",
      },
      {
        id: 1,
        name: "Vivian Reeves",
      },
      {
        id: 2,
        name: "Sykes Bernard",
      },
    ],
    greeting: "Hello, Mendoza Pollard! You have 4 unread messages.",
    favoriteFruit: "banana",
  },
];
